# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:25
from __future__ import unicode_literals

from django.db import migrations



def separate_users(apps, schema_editor):
    User = apps.get_model('everything', 'User')
    User_User = apps.get_model('users', 'User')

    for old_user in User.objects.all():
        User_User.objects.create(uuid=old_user.uuid,
                                email=old_user.email)


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0003_auto_20170425_1622'),
    ]

    operations = [
            migrations.RunPython(separate_users),
    ]
