# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0004_auto_20170425_1649'),
        ('everything', '0005_auto_20170425_1725'),
    ]

    operations = [
    ]
