# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(through='comments.Comment', to='users.User'),
        ),
    ]
