# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.UUIDField()),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.User'),
        ),
    ]
